### PR TITLE
Fix filepath handling in compile script for non-ascii characters.

### PR DESCRIPTION
**Pull request by joshi-monster**
Fixes 2 bugs:

1. `file:read_line` does not return the correct thing when reading non-ascii characters from rust. This caused the escript to create mojibake directories.
2.  `erlang:display` does not use unicode, which makes the Rust side unable to parse its output and return an error.

~~I will try this again tomorrow on my windows machine once I'm at work. I'm also too tired I think to trust myself to not have done something stupid here.~~

update:
`file:read_line` isn't a problem on windows, since the shell uses an entirely different way to for io
`erlang:display` is not a problem in production, only if `GLEAM_LOG=trace` is enabled on all platforms.

### CODE REVIEW

**Comment by joshi-monster** [comment]
I left it on draft because I wanted to add that test tonight :D

**Comment by lpil** [comment]
Thank you!

**Comment by joshi-monster** [comment]
I managed to replicate the issue in #3914, and this PR also seems to fix that one. The trace output is still kinda broken (printing the erlang charlist as a list instead of as a string), but at least it compiles successfully with and without having trace active, and doesn't create mojibake anymore.

**Review by lpil — APPROVED** [review]
Lovely work! Thank you

**Pull request merged**
