### PR TITLE
Rename modulo to remainder

### PR DESCRIPTION
**Pull request by inoas**
Fixes https://github.com/gleam-lang/gleam/commit/7d1ebf20a7f96f36d63c5f182a9cfd2be1d47336#commitcomment-86422710

How would I run these gleam tests locally: https://github.com/gleam-lang/gleam/compare/main...inoas:gleam-src:rename-modulo-to-remainder?expand=1#diff-9d3bd960f2c78cd4cc676f5d6d004518bef3e64b47c22cc012db04608140ca3aR1171-R1175

Edit: I was told `make test` :)

### CODE REVIEW

**Comment by inoas** [comment]
I have added the other remainder tests because some languages decide to handle negative values differently (to Erlang/Elixir/C/JS) in case we ever target another VM/native.

**Review by lpil — COMMENTED** [review]
Thanks! Could you also rename it in the AST? On the BinOp type

**Comment by inoas** [comment]
> Thanks! Could you also rename it in the AST? On the BinOp type

Done, I don't know why that one eluded me.

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
