### PR TITLE
feat: initialize git repo when creating a new project

### PR DESCRIPTION
**Pull request by wesleimp**

### CODE REVIEW

**Comment by michallepicki** [comment]
@wesleimp Does it succeed and just skip the step if there's no git installed in the system?

**Comment by wesleimp** [comment]
> @wesleimp Does it succeed and just skip the step if there's no git installed in the system?

Yes, it does.

**Review by lpil — COMMENTED** [review]
Great stuff!

Looking at the `git2` project it depends on the libgit C library. Could we instead use the `git` command line? We could check to see if git is installed first and do nothing if it is not.

There's already code for running shell commands so we can reused that.

**Review by lpil — COMMENTED** [review]
Looking great! Would you mind updating the CHANGELOG file with a `## Unreleased` section at the top?

Thank you

**Review by lpil — APPROVED** [review]
Fantastic, thank you!

**Comment by lpil** [comment]
I've rebased these changes onto the main branch, thank you

**Pull request closed without merging**
