### PR TITLE
Add Negation Operator

### LINKED ISSUE #1330: Negation Operator
We need a way to negate booleans in a `case` guard statement.

`if !some_bool -> …`

### PR DESCRIPTION
**Pull request by HarryET**
This closes #1330 by adding the bang (`!`) operator to Gleam.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Looking great so far! Just needs tests for typing, Erlang, JS, and formatting.

**Comment by lpil** [comment]
@HarryET Is there anything you could do with some pointers on here?

**Comment by HarryET** [comment]
> @HarryET Is there anything you could do with some pointers on here?

Yeah @lpil, I'm unsure as to where the tests go. And when testing locally it appears that it can't parse the bang character.

**Comment by lpil** [comment]
A test [like this](https://github.com/gleam-lang/gleam/blob/2adb6f921f5d08bf1fa44506ab1a8c140eefe341/compiler-core/src/type_/tests.rs#L1859-L1868) that checks that this function takes and returns a bool would be good

```gleam
pub fn negate(x) {
  !x
}
```

Then one for a type error coming from `!` being used with something other than a bool  https://github.com/gleam-lang/gleam/blob/2adb6f921f5d08bf1fa44506ab1a8c140eefe341/compiler-core/src/type_/tests/errors.rs#L1549-L1561

Then one for the Erlang it compiles to https://github.com/gleam-lang/gleam/blob/2adb6f921f5d08bf1fa44506ab1a8c140eefe341/compiler-core/src/erlang/tests.rs#L399-L411


Then one for the JS it compiles to https://github.com/gleam-lang/gleam/blob/2adb6f921f5d08bf1fa44506ab1a8c140eefe341/compiler-core/src/javascript/tests/bools.rs#L101-L112

And lastly one for the formatter https://github.com/gleam-lang/gleam/blob/2adb6f921f5d08bf1fa44506ab1a8c140eefe341/compiler-core/src/format/tests.rs#L3303-L3314

You will need to install `cargo-insta` if you have not already with `cargo install cargo-insta`.

I can help with the parsing once we have some failing tests that show the problem

**Comment by lpil** [comment]
How's this going @HarryET ? :)

**Comment by HarryET** [comment]
> How's this going @HarryET ? :)

Slowly @lpil 😅

**Comment by lpil** [comment]
Let me know if you would like me to take a look 👍

**Comment by HarryET** [comment]
> Let me know if you would like me to take a look 👍

Any chance you could give me a hand @lpil, I can't figure out what's wrong.

**Pull request merged**
