### PR TITLE
added replace flag

### PR DESCRIPTION
**Pull request by massivefermion**
together with [this](https://github.com/gleam-lang/hexpm-rust/pull/15), address [this](https://github.com/gleam-lang/gleam/issues/1425)

### CODE REVIEW

**Comment by lpil** [comment]
Hello! Would you like me to take over this PR or would you like to update it? I have published the new Hex package

**Comment by massivefermion** [comment]
Sorry, I forgot about that
it's using the correct version now

**Review by lpil — COMMENTED** [review]
Brilliant! Would you mind updating the changelog file too?

I may wait until after this release is out to merge 🙏

**Review by lpil — APPROVED** [review]
Thank you 💜 💜 💜

**Pull request merged**
