### PR TITLE
Remove `local` when loading fonts in generated docs

### LINKED ISSUE #2208: Docs font not loading properly in Chrome
Today I discovered that the font used in the docs generated by Gleam ("Karla") is not loading properly in Chrome.

In docs generated by older versions of Gleam (v0.22) the font is loaded from Google Fonts and loads fine:

Screenshot 2023-05-31 at 8 58 12 PM

https://hexdocs.pm/gleam_bitwise/index.css?v=0.22.0-dev

However, when loading docs generated by the current version of Gleam (v0.29) the font is loaded from local font files and does not load fine in Chrome, which results in the docs falling back to the system font:

Screenshot 2023-05-31 at 8 58 22 PM

https://hexdocs.pm/glenvy/css/index.css?v=0.29.0

While trying to troubleshoot the issue I discovered that docs generated by Gleam v0.29 do show the proper font in Safari:

Screenshot 2023-05-31 at 9 25 04 PM

So it seems like a browser-specific issue (at least impacting Chrome, I haven't tested other browsers).

My original Discord post: https://discord.com/channels/768594524158427167/1113633239077240862

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR removes the `local` function in the `@font-face` rules used to load fonts in the docs.

### Motivation

Removing the `local` function and always loading the font from the URL fixes an issue where fonts would sometimes not load properly (observed in Chrome on macOS).

Looking at the Google Fonts URL that we [used to load](https://github.com/gleam-lang/gleam/commit/4ec57a689c6637aad9b2076f5610cd67409f1590#diff-0a2b885976116f3f1750e64dbd5bad302d7261a174ec104e53b48940ee765e67L1):

```css
@import url("https://fonts.googleapis.com/css2?family=Karla:wght@400;700&family=Ubuntu+Mono&display=swap");
```

If we load this URL directly now this is what we get back: https://gist.github.com/maxdeviant/4ef9752063fbcb0ad15bb2cc0d2229b6

Notably, what _isn't_ present (at least at time of writing) is any use of `local()`:

```css
/* latin-ext */
@font-face {
  font-family: 'Karla';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/karla/v30/qkB9XvYC6trAT55ZBi1ueQVIjQTD-JrIH2G7nytkHRyQ8p4wUjm6bmMorHBiTg.woff2) format('woff2');
  unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
```

### Explanation

After removing the `local()` function calls I observed that the fonts now load properly across all of the browsers, including the one where it wasn't before.

There shouldn't be any reason to use `local()`, as it's quite unlikely that anyone will already have these fonts present on their system. And even if they do, the overhead of downloading a font file that we distribute is going to be negligible. 

Fixes #2208.

### CODE REVIEW

**Comment by maxdeviant** [comment]
After making this change I tested the output from `gleam build docs` with a `gleam` executable built with these changes.

I observed the fonts loading in all browsers I have on this machine:

#### Chrome

This is the browser that wasn't rendering the fonts properly before.

Screenshot 2023-05-31 at 10 54 34 PM

#### Firefox

Screenshot 2023-05-31 at 10 56 07 PM

#### Safari

Screenshot 2023-05-31 at 10 56 18 PM

**Comment by maxdeviant** [comment]
@NthTensor Would you be up for testing out these changes locally to see if they work for you?

**Comment by NthTensor** [comment]
Works great on firefox/linux. Good work, and sorry for the confusion last night.

**Comment by inoas** [comment]
> This PR removes the `local` function in the `@font-face` rules used to load fonts in the docs.
> ### Motivation
> 
> Removing the `local` function and always loading the font from the URL fixes an issue where fonts would sometimes not load properly (observed in Chrome on macOS).
> 
> Looking at the Google Fonts URL that we [used to load](https://github.com/gleam-lang/gleam/commit/4ec57a689c6637aad9b2076f5610cd67409f1590#diff-0a2b885976116f3f1750e64dbd5bad302d7261a174ec104e53b48940ee765e67L1):
> 
> ```css
> @import url("https://fonts.googleapis.com/css2?family=Karla:wght@400;700&family=Ubuntu+Mono&display=swap");
> ```
> 
> If we load this URL directly now this is what we get back: https://gist.github.com/maxdeviant/4ef9752063fbcb0ad15bb2cc0d2229b6
> 
> Notably, what _isn't_ present (at least at time of writing) is any use of `local()`:
> 
> ```css
> /* latin-ext */
> @font-face {
>   font-family: 'Karla';
>   font-style: normal;
>   font-weight: 400;
>   font-display: swap;
>   src: url(https://fonts.gstatic.com/s/karla/v30/qkB9XvYC6trAT55ZBi1ueQVIjQTD-JrIH2G7nytkHRyQ8p4wUjm6bmMorHBiTg.woff2) format('woff2');
>   unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
> }
> ```
> 
> ### Explanation
> 
> After removing the `local()` function calls I observed that the fonts now load properly across all of the browsers, including the one where it wasn't before.
> 
> There shouldn't be any reason to use `local()`, as it's quite unlikely that anyone will already have these fonts present on their system. And even if they do, the overhead of downloading a font file that we distribute is going to be negligible.
> 
> Fixes #2208.

- local usage was on purpose so that users can configure the fonts of generated documents per system
- local rendering wrong may be due to bad local fonts installed or bad browser handling (specifically on linux)
- removing local isn't a big deal, there are reasons to keep it but the gains are small, so 👍🏼 for removing if it caused troubles (despite that the source is browser/font file related, not local related)

**Review by lpil — APPROVED** [review]
Seems reasonable to me. Thanks for digging into this folks.

Mind updating the changelog also? Thank you

**Comment by maxdeviant** [comment]
> Seems reasonable to me. Thanks for digging into this folks.
> 
> Mind updating the changelog also? Thank you

Done!

**Comment by maxdeviant** [comment]
Huh, CI seems unhappy 🤔

**Review by lpil — APPROVED** [review]
Thanks!!

The linter seems broken. We can ignore that.

**Pull request merged**
