### PR TITLE
lsp: Watch for gleam.toml paths in worktrees

### PR DESCRIPTION
**Pull request by osiewicz**
Currently Gleam Language Server watches for changes to **/gleam.toml - which is a global path. This is probably undesired, as we only really need to watch for changes in the worktree this server is spawned for. 
This PR uses workspace_folders provided by clients to root the watched paths.

This came up (and unsurfaced a bug) in https://github.com/zed-industries/zed/pull/17206.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Thank you. Could you extract this to a helper function and add a test for it please 🙏 

The changelog will need to be updated too.

Please un-draft when you are ready for a review.

**Review by lpil — APPROVED** [review]
Beautiful!! Thank you

Could you rebase to remove the merge commit please 🙏

**Comment by lpil** [comment]
Oh dear! Looks like CI is failing

**Comment by lpil** [comment]
When you are ready for a review please un-draft this PR. Thank you!

**Comment by lpil** [comment]
Hello! Are you still working on this one? Thanks

**Comment by osiewicz** [comment]
Hey,
Not gonna lie, I've opened it as a bit o a drive-by while I was looking at a crash of Zed related to Gleams handling of watched paths; I don't really have time to drive this across the line and we've adjusted our handling since, so I think it should be okay to close this out for the time being. Sorry for wasting your time!

**Pull request closed without merging**
