### PR TITLE
Disallow the utf type specifiers in bit string matching

### LINKED ISSUE #744: uft8 and uft8_codepoint both match as a utf8_codepoint type
I might be wrong in my understanding of the expected behaviour but I believe the following is a bug.

I think this code should compile
```rust
  let <<"ab":utf8, rest:utf8>> = "abcd"
  should.equal("cd", rest)
```

it however fails because the type of rest is `UtfCodepoint`.
My assumption is if the match was to say `rest:utf8_codpoint` explicitly then the type of rest should be UtfCodepoint and this would be the correct compilaton failure. However I think that `rest:utf8` should return rest with a type of string.

### PR DESCRIPTION
**Pull request by tomwhatmore**
Closes #744

### CODE REVIEW

**Comment by tomwhatmore** [comment]
Not sure why the build is failing on mac os, it just says `can't find crate for 'serde_derive' which 'lalrpop' depends on`. Any ideas @lpil ?

**Review by lpil — APPROVED** [review]
Thank you.

I don't understand what's happening with the OSX build but it has started doing this a lot lately. I found a similar looking issue in the Rust tracker and it suggested there was a bug in BSD tar of all things!

**Comment by tomwhatmore** [comment]
That's annoying! Thanks for the info, I have to admit that bug in BSD tar would have been quite far down my list of guesses.

**Comment by lpil** [comment]
I find it baffling. I'm interested in seeing whether #782 helps

**Pull request merged**
