### PR TITLE
feat(lsp): complete variables

### PR DESCRIPTION
**Pull request by saiintbrisson**
Adds a naive implementation of variable name completion for the current scope. Please judge! This was put together in about 1 hour of getting to know the codebase, I have no idea if it is correct.

image
image

### CODE REVIEW

**Comment by saiintbrisson** [comment]
Oh wait, I'll add arguments and consts as well. Forgot about those.

**Comment by saiintbrisson** [comment]
Next step is probably some sort of sorting of completions based on the expected type. Better leave it to another PR

**Comment by saiintbrisson** [comment]
I should probably evaluate whether the cursor if before or after the variable assignment shouldn't I...

**Comment by saiintbrisson** [comment]
r-a has deeper access to information regarding the local variables, like `Environment.scope` has, but I gather the LSP can't access an `Environment`?

**Comment by lpil** [comment]
Aye, the environment is an internal detail of the analysis code, by this point it does not exist. I think we would implement this by building and then inspecting a call graph.

**Comment by saiintbrisson** [comment]
@lpil I think I got it working in almost all cases (or at least those I can think of).

But here's the thing, I went with a recursive approach descending all expressions surrounding the cursor, shouldn't be a problem in most cases, but can be inefficient with complex expression chains and long statements. We can build the call graph and than keep it in memory as long as the source is valid, but I don't really know where to start and what it should look like.

Another thing bugging me is that `engine.rs` will eventually become a mess. Should we relocate completions to something like `engine/completions.rs`?

Lemme know if the current way of doing things is acceptable for now, or if you prefer we hold the idea until we have a clearer idea of how to implement it.

**Comment by lpil** [comment]
Hello! The way to implement this is to build a call graph during compilation and persist that, and then perform a lookup on that graph to get what's currently in scope.

Hold off on splitting any modules for now 👍

**Comment by lpil** [comment]
Closing due to inactivity. Please feel free to reopen! Thank you

**Pull request closed without merging**
