### PR TITLE
add hex plugin to library projects

### PR DESCRIPTION
**Pull request by CrowdHailer**

### CODE REVIEW

**Comment by lpil** [comment]
What does this enable?

**Comment by CrowdHailer** [comment]
It is needed to publish a package to hex

**Comment by lpil** [comment]
Is that right? How come I haven't needed that for anything I have
published? For example the stdlib

**Comment by CrowdHailer** [comment]
Maybe we're publishing different ways?
Maybe your local setup has it installed globally?

**Comment by lpil** [comment]
The Hex docs say this should be added globally, so I think that's the way to go https://hex.pm/docs/rebar3_publish

**Pull request closed without merging**
