### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by CrowdHailer**

### CODE REVIEW

**Review by wesleimp — APPROVED** [review]

**Review by lpil — APPROVED** [review]
Thank you

**Comment by CrowdHailer** [comment]
Go for it. I only have the github ui so will be a pile of commits from me

**Comment by CrowdHailer** [comment]
I had assumed the snapshots where generated?

**Comment by lpil** [comment]
They are but it's a manual step to ensure that any changes in format is intentional. I'll cherry pick this onto my branch 👍

**Pull request closed without merging**
