### PR TITLE
Warn for redundant capture

### LINKED ISSUE #2999: Add diagnostic for unnecessary function capture
Thanks for all the work that has gone into the language and the diagnostics, they truly are amazing!

While going through the tutorial, it occurred to me after I wrote this and then removed the `(_)` that the function capture was completely unnecessary, but with no warning I'm sure this error exists in a ton of codebases already, and could be easily dealt with with a diagnostic added to the compiler.

```gleam
  1
  |> int.to_string(_) // <-- (_) is unnecessary and can be removed without changing the meaning of the pipeline
  |> string.repeat(5)
  |> string.drop_left(2)
  |> io.println
```

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This PR closes #2999

### CODE REVIEW

**Comment by lpil** [comment]
Linter is failing!

**Comment by giacomocavalieri** [comment]
Oops, should be all good now!

**Review by lpil — APPROVED** [review]
Nice! Thank you

**Comment by nicklimmm** [comment]
The current implementation outputs false positives for `_` not in the first argument.

A reproducible example:

image

**Comment by giacomocavalieri** [comment]
Oops my bad, I'll fix it!

**Pull request merged**
