### PR TITLE
Determine removed package exists for `gleam remove`

### LINKED ISSUE #3279: `gleam remove` always reports a removal, even if the package did not exist in `gleam.toml`
To reproduce, run `gleam remove <package>` using any arbitrary input, such as `gleam remove doesntexist`:
```
vxern@Dorian tatoeba % gleam remove doesntexist
    Removed doesntexist
```

Gleam version: `v1.2.1`

### PR DESCRIPTION
**Pull request by hnlcf**
Fix #3279

### CODE REVIEW

**Comment by markholmes** [comment]
What does the output look like with this fix? Do you have an example?

**Comment by hnlcf** [comment]
For non-existent packages, the `print_colourful_prefix` function is currently used to print `Not Exist`

lalala

**Review by lpil — COMMENTED** [review]
Thank you.

Could you return an Error variant instead? And put the printing back to the end.

**Comment by hnlcf** [comment]
OK, I return error instead for non-existent packages. 

image

**Review by lpil — APPROVED** [review]
Thank you

**Pull request merged**
