### PR TITLE
Fix code generation when calling functions returned through field access

### LINKED ISSUE #580: Invalid Erlang generated when calling function returned by accessor
```rust
some_record.field()
```

This generates this Erlang

```erlang
erlang:element(2, SomeRecord)()
```

Which is invalid, it need to be this:

```erlang
(erlang:element(2, SomeRecord))()
```

We will also have the same problem for accessing tuples.

### PR DESCRIPTION
**Pull request by QuinnWilton**
Resolves #580

### CODE REVIEW

**Comment by lpil** [comment]
Would you mind updating the changelog? Thanks

**Comment by lpil** [comment]
oops, merge conflict. Sorry, could you fix that?

**Comment by QuinnWilton** [comment]
Yup, on it :)

**Comment by QuinnWilton** [comment]
Fixed! One day I'll remember to update the changelog on my own. Do you think it's worth adding a PR template that includes that on a checklist?

**Comment by lpil** [comment]
> Do you think it's worth adding a PR template that includes that on a checklist?

If it's possible to add them for only PRs then that sounds good

**Pull request merged**
