### PR TITLE
Make sure the export package-interface command uses the project's cache

### LINKED ISSUE #2614: `gleam export package-interface` recompiles project and dependencies every time
When running `gleam export package-interface` it recompiles the project and dependencies from scratch every time, maybe it should be using the project's cache to avoid recompiling everything.

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This PR closes #2614

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
This will make it so deleted modules will show up in the interface. Is that OK?

**Comment by giacomocavalieri** [comment]
Aha! That didn't occur to me, what would you say is best here? It shouldn't be a problem for published packages because the compiler rebuilds everything before publishing, but it could lead to some confusing errors when used locally 🤔

**Comment by lpil** [comment]
Maybe we just accept the bug for now?

**Comment by giacomocavalieri** [comment]
I'd say yeah I don't see that being a big source of bugs and we can always go back to deleting the cache (or finding an actual fix for when modules are deleted) if it turns out to be a bigger problem

I'd open an issue or add a TODO comment in the code to not forget about this, though. I can totally see myself forgetting about this quirk in a week 😂

**Comment by lpil** [comment]
I think this issue will cover it: https://github.com/gleam-lang/gleam/issues/1970

**Review by lpil — APPROVED** [review]
Thanks!

**Pull request merged**
