### PR TITLE
Fixed windows tests

### LINKED ISSUE #299: Fix tests on Windows

### PR DESCRIPTION
**Pull request by thehabbos007**
Hopefully it works on CI too :)
closes #299

### CODE REVIEW

**Comment by lpil** [comment]
Oh neat! Does the compiler work on Windows now? Have you been able to test it on windows for creating and compiling projects?

**Comment by thehabbos007** [comment]
> 
> 
> Oh neat! Does the compiler work on Windows now? Have you been able to test it on windows for creating and compiling projects?

I'll try it out. Will take some minutes :)

**Comment by lpil** [comment]
Thank you

**Comment by thehabbos007** [comment]
@lpil It seems to be working, even with multiple files and imports. Any further testing you want me to try? One thing is that the stdlib isn't present, but i assume it isn't when using the make target for installing, correct?

**Comment by lpil** [comment]
Great, thank you!

The stdlib is distributed as a hex package and so it should be pulled down by rebar3 in Gleam projects

**Pull request merged**
