### PR TITLE
Port `entrypoint.sh` for PowerShell

### PR DESCRIPTION
**Pull request by bunopnu**
addresses #2380

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Wonderful! Thank you!

There's a test for this here

https://github.com/gleam-lang/gleam/blob/91df6e02cb59c0510b7b0a799a9405a5de5d8bc3/.github/workflows/ci.yaml#L121-L127

Would you mind making this run on Windows too? And updating the CHANGELOG.md file.

**Comment by bunopnu** [comment]
It appears that the [Windows Test](https://github.com/bunopnu/gleam/actions/runs/6657111450/job/18091133643) is encountering a failure, due to issues with the compilation of the `bcrypt` module. The easiest solution might be to replace `bcrypt` with a more straightforward alternative, and it seems that this is currently marked as a TODO.

I'd like to hear your thoughts, @lpil

**Comment by lpil** [comment]
Bcrypt is deliberately there to ensure that nifs work, but I guess they do not on Windows! or at least not that one.

Having a minimal project that doesn't use a nif and testing that on windows would be good for now, until we work out what is wrong with the full one.

**Comment by bunopnu** [comment]
I've made a copy of `project_erlang` called `project_erlang_windows`. The main differences are that I've updated the dependencies and left out bcrypt.

I think it is ok for now and can be removed after replacing `bcrypt` with something that supports all three major platforms (maybe something that uses rustler?)

**Comment by lpil** [comment]
> I think it is ok for now and can be removed after replacing bcrypt with something that supports all three major platforms (maybe something that uses rustler?)

I don't want to use ruster, I want to use regular NIFs as this is a more useful and realistic test.

I didn't realise that library doesn't support Windows! That is very disappointing.

**Review by lpil — APPROVED** [review]
Thank you!!

**Comment by lpil** [comment]
I have rebased these onto the main branch, thank you very much!

**Pull request closed without merging**
