### PR TITLE
Add subcommand for generating shell completion scripts

### PR DESCRIPTION
**Pull request by tranzystorek-io**
Since clap gives those basically for free 😄

### CODE REVIEW

**Comment by lpil** [comment]
Very cool! How do we use it?

**Comment by tranzystorek-io** [comment]
@lpil depends on script, but basically for example `gleam completion zsh > <completion_dir>/_gleam`, usually package maintainers put them in global completion paths like `/usr/share/bash-completion/completions/` or `usr/share/zsh/site-functions/`

**Comment by tranzystorek-io** [comment]
A user typically configures a local completion directory and adds it to an env var like `FPATH` in zsh

**Comment by tranzystorek-io** [comment]
Ugh, seems `AppSettings::Hidden` doesn't hide commands from the completion generator

obraz

**Comment by lpil** [comment]
Hmm, that is a bit annoying. It could be OK if we remove the print-config command.

Perhaps newer versions of clap might hide them? It seems odd they are not hidden.

**Comment by tranzystorek-io** [comment]
> Perhaps newer versions of clap might hide them?

Did a quick check on clap 3.0.0-beta.5 for my own project, hidden apps still show up in scripts 🙁

**Comment by lpil** [comment]
It looks like it will be fixed in a future release? https://github.com/clap-rs/clap/issues/2541

**Comment by tranzystorek-io** [comment]
From the discussion it seems the status is back to [#1335](https://github.com/clap-rs/clap/issues/2541#issuecomment-991113676)

**Comment by lpil** [comment]
Ah, that is a shame

**Comment by lpil** [comment]
I'm going to close this as we're a bit stuck, but please reopen once we can hide commands.

**Pull request closed without merging**
