### PR TITLE
LSP: Assign unused Result value to `_`

### LINKED ISSUE #2960: LSP code action: add `let _ =` to focused unused value

### PR DESCRIPTION
**Pull request by Frank-III**
Hopefully resolve #2960.

Try to implement the second-way @lpil proposed in #3255, please review my code 🙏.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Hello! Could you rebase to resolve the merge conflicts please.

**Comment by lpil** [comment]
Sorry, we don't permit merge commits here, it needs to be a rebase. Or I could I squash this PR if you prefer!

**Comment by Frank-III** [comment]
Sorry about that! Let me close this as #3415 is merged

**Comment by lpil** [comment]
Coolio! Do you want to open a new PR or?

**Comment by Frank-III** [comment]
I would try if I could do it within `LanguageServerEngine`

**Pull request closed without merging**
