### PR TITLE
documentation generator improvements

### PR DESCRIPTION
**Pull request by inoas**
- As far as I understand this closes the 2nd part of https://github.com/gleam-lang/gleam/issues/1727
- Closes https://github.com/gleam-lang/gleam/issues/1804
- Closes https://github.com/gleam-lang/gleam/issues/1730 except for the google web fonts dependency, still on my TODO for this PR

- Cleans up the template dir a bit because, it seems (to me) that there is a mix of docs and other templates
- Adds files to exist in ci test setting
- Moves all assets (but one, for now), into the generated docs assets
- Visually: Widens content on regular displays to display at least 80 symbols of source code
- Visually: Generally moves headers closer to their contents
- Removes a lot of `:hover` `text-decorations:underline` and replaces them with other effects, such as a paragraph symbol or a slight background
- Enlarges clickable list items on the sidebar vertically (easier to click, esp on mobile), removing margins
- Styles the clickable version select so it is clear what it does. Moves the arrow to the front because we can't (easily) know the select box width (there are better more sophisticated ways that take more code/thinking)
- Only truncate project title if necessary on mobile
- Search input bar will shrink if the title is longer, but the result bar will stay as wide as the main content bar on desktop (mobile behavior untouched in this regard)
- Search input bar replaces header on mobile as before, but now does not change height anymore

### CODE REVIEW

**Comment by inoas** [comment]
Also fixed constructors, here are some screenshots:

Screen Shot 2022-10-30 at 06 12 09
Screen Shot 2022-10-30 at 06 11 12
Screen Shot 2022-10-30 at 05 56 18
Screen Shot 2022-10-30 at 05 55 56
Screen Shot 2022-10-30 at 05 55 46
Screen Shot 2022-10-18 at 22 58 58

**Comment by inoas** [comment]
Also updated all the highlight deps to latest stable 11.6 from 10.5 or so.

**Comment by inoas** [comment]
... and included javascript highlight deps, so people should be able to use ` ` ` javascript  markdown blocks

**Comment by inoas** [comment]
To get the woff2 files into the docs, I would like to change the `text: String` part of `OutputFile` to `Vec<u8>` and then do not pass some files through the templating such as binaries or js/css libs. Is this a good way forward or do you imagine another way?

**Comment by inoas** [comment]
before:
Screen Shot 2022-10-31 at 15 22 23

after:
Screen Shot 2022-10-31 at 15 22 25

before:
Screen Shot 2022-10-31 at 15 22 30

after:
Screen Shot 2022-10-31 at 15 22 34

before:
Screen Shot 2022-10-31 at 15 22 59

after:
Screen Shot 2022-10-31 at 15 23 00

before:
Screen Shot 2022-10-31 at 15 23 03

after:
Screen Shot 2022-10-31 at 15 23 06

before:
Screen Shot 2022-10-31 at 15 25 24

after:
Screen Shot 2022-10-31 at 15 25 26

before:
Screen Shot 2022-10-31 at 15 25 30

after:
Screen Shot 2022-10-31 at 15 25 33

before:
Screen Shot 2022-10-31 at 15 25 38

after:
Screen Shot 2022-10-31 at 15 25 40

before:
Screen Shot 2022-10-31 at 15 25 43

after:
Screen Shot 2022-10-31 at 15 25 48

**Comment by inoas** [comment]
Constructor alignment and star icon size and colour:

before
Screen Shot 2022-10-31 at 16 29 46

after
Screen Shot 2022-10-31 at 16 29 48

**Comment by lpil** [comment]
This PR does 13 things, is large, and is hard to review as a result! Please submit one PR per change or per group of related changes 🙏

**Comment by inoas** [comment]
> This PR does 13 things, is large, and is hard to review as a result! Please submit one PR per change or per group of related changes 🙏

Okay, my current plan is:

1. Move static assets local and omit passing them through the templater and add woff2 => https://github.com/gleam-lang/gleam/pull/1819
2. Update the header project-version and search bar changes
3. Increase the width of the main window so 80em of code are visible
4. Cosmetic CSS changes to improve margins/paddings and mobile UX

**Pull request closed without merging**
