### PR TITLE
Update dependencies and move common ones to the workspace `Cargo.toml`.

### LINKED ISSUE #2723: Update compiler dependencies and move common ones to the workspace `Cargo.toml`
It'd be convenient to have all the common deps in the workspace `Cargo.toml`, so that versions are guaranteed to be consistent among the subcrates using them.

### PR DESCRIPTION
**Pull request by DanikVitek**
Closes #2723

### CODE REVIEW

**Comment by DanikVitek** [comment]
It's also possible to move some common `[package]` keys to the workspace `Cargo.toml` like `version`, `edition`, and `authors`

**Comment by DanikVitek** [comment]
Clap 4.5 needs to be re-configured to have colors, sort commands alphabetically, and show the version number at once.

**Review by lpil — APPROVED** [review]
Fantastic work! Thank you so much!

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
