### PR TITLE
Use `.d.mts` extension for ts type declarations

### PR DESCRIPTION
**Pull request by vonagam**
Gleam generates `.mjs` files but instead of `.d.mts` it generates `.d.ts`. This mismatch prevents typescript from finding corresponding type declarations. Ability to find those declarations depend on t sconfig and resolver - some things did work for me with current `.d.ts` extension, others were producing errors, with `.d.mts` all bases are covered.

This PR is based on previous one, will rebase once it is merged or rejected.

### CODE REVIEW

**Comment by lpil** [comment]
Thank you.

I'm not familiar with .mts files. Is there a place I can read more? Or how would I replicate the issue?

**Comment by vonagam** [comment]
Ok, I've updated changelog for PR about `import type`. When it is merged I'll rebase and update changelog here.

**Comment by vonagam** [comment]
I've rebased this PR and dollar one. Let me know if there is anything else to be done here.

**Review by lpil — APPROVED** [review]
Thank you so much!!

**Pull request merged**
