### PR TITLE
Improve snapshot format for error snapshots

### PR DESCRIPTION
**Pull request by GearsDatapacks**
Part of #3736 
This PR adds the source code causing the error to the snapshots for error tests.

### CODE REVIEW

**Comment by GearsDatapacks** [comment]
Should the `assert_with_module_error` snapshots also contain the source code for the other modules?

**Comment by lpil** [comment]
That's a nice idea, yes please!

**Comment by GearsDatapacks** [comment]
Alright. I'll add that then. I think there are some similar things in the javascript tests, so I can add it to them too

**Review by lpil — APPROVED** [review]
Hero! Thank you!!

lol this PR is making my computer lag hard

**Pull request merged**
