### PR TITLE
Mark module alias access in pattern as 'used'

### PR DESCRIPTION
**Pull request by michaeljones**
This is an attempt to fix: https://github.com/gleam-lang/gleam/issues/3313

I don't have any experience with the code base. This is an educated guess based on grepping and fixing the added test.

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Lovely! Thank you. Would you mind updating the changelog also?

**Comment by michaeljones** [comment]
Glad it seem suitable.

I've added a changelog entry now.

**Comment by michaeljones** [comment]
I've adjusted the test name and added a link to the issue too (as it is quite a specific thing.)

**Review by lpil — APPROVED** [review]
Lovely, thank you

**Pull request merged**
