### PR TITLE
Allow gleam new in existing directories

### LINKED ISSUE #1879: Support creating a new Gleam project in the current directory with `gleam new .`
Apparently not is possible to create a Gleam project in your current directory.

Example:

image

### PR DESCRIPTION
**Pull request by abs0luty**
Resolves #1879
Duplicate of #2459

### CODE REVIEW

**Comment by abs0luty** [comment]
@lpil Created a new PR without all the garbage made by rebasing main.

**Review by lpil — COMMENTED** [review]
Could you rebase on main to remove the merge commit and to fix the conflicts? Thank you.

**Comment by abs0luty** [comment]
@lpil Removed the merge commit as you've said!

**Comment by lpil** [comment]
Sorry, there's a merge conflict now. Could you update that please?

**Pull request merged**
