### PR TITLE
Change search bar background color

### LINKED ISSUE #2540: (Docs theme) Search bar should have a darker background
Currently, the search bar in generated docs has a `transparent` background. This impacts discovery and makes the bar harder to find.

image

The color of the bar when `active` is perfect.

image

I think that the bar should be that color regardless of when active or focused. The icon should still change color and the page should still be dimmed. Like this:

msedge_gGuMRWvpI7

I am happy to submit a PR for this if approved!

### PR DESCRIPTION
**Pull request by MystPi**
Fixes #2540.

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Thank you! Would you mind updating the changelog too please? Thanks

**Comment by MystPi** [comment]
Sure thing! I am confused where to write the changes though. Should I note them in an existing section or create a new one?

**Comment by lpil** [comment]
The build tool section works 👍

**Comment by MystPi** [comment]
Sorry, I meant which version to put the changes under (such as `v0.34.0-rc3 - 2023-01-12`).

**Comment by lpil** [comment]
I normally go for "## Unreleased"

**Comment by MystPi** [comment]
Thank you! I have updated the changelog.

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
