### PR TITLE
Feat: add annotation LSP code action

### LINKED ISSUE #2953: LSP code action: add annotation to assignment

### LINKED ISSUE #2954: LSP code action: add annotations to module function
Follows on from https://github.com/gleam-lang/gleam/issues/2953

### PR DESCRIPTION
**Pull request by raquentin**
Closes #2953. Added LSP code action to add explicit type annotations to assignments.

Closes #2954. Added LSP code action to add explicit type annotations to module functions. 

This implementation is inevitably opinionated, I tried to match precedence where it exists but with only 1 other code action there wasn't much. Any changes lmk

Changes:
- added new code action handler `code_action_add_annotation`
- added `code_action_add_annotation` call in LSP engine
- added function `name_if_self_is_var` to `TypedPattern` in `ast.rs` for use in code action suggestion text
- added function `find_nodes_in_range` to `Module` in `build.rs`
- re-organized LSP code action test file a bit to scale better with more code actions
- added LSP test for both annotation types, tested extensively via lsp

Implementation Details:
- this code action is suggested when the start of the selection/cursor is within a line containing an assignment/func
- assignment var name/func name (if applicable) and type is shown in the suggestion:
image
- the abstraction of two helper funcs out of the code action for use in future code actions (primarily), see changes

### CODE REVIEW

**Comment by raquentin** [comment]
Can't really track down that failed check, might be a problem on hex's side

**Comment by Acepie** [comment]
That seems to just happen sometimes lately. You can probably just make a dummy/empty commit if you wanna rerun the pipeline

**Comment by raquentin** [comment]
Marked as draft to clean it up a bit and add test

**Review by lpil — COMMENTED** [review]
Hello! I've not reviewed this fully yet but I can see it's using the type printer which is not suitable for code generation, it will output a representation that is not valid in many cases. This PR is making a printer is that is suitable: https://github.com/gleam-lang/gleam/pull/3007

Could you split up the tests to have one test per thing being tested, and we'll need test coverage for imported types, shadowed types, used but not imported types, aliased types, qualified aliased types, and function types.

Thank you

**Comment by raquentin** [comment]
Hi, and sounds good, once #3007 is merged I'll plug it in. And yes, I can expand the test suite as well

**Comment by lpil** [comment]
Closing due to inactivity. Please feel free to reopen! Thank you

**Comment by raquentin** [comment]
reopening as #3007 has been merged

**Pull request closed without merging**
