### PR TITLE
Bundle JS and CSS instead of relying on unpkg CDN

### PR DESCRIPTION
**Pull request by aflatter**
This PR introduces a build step for the assets required to serve the documentation in order to make it usuable without an internet connection (see #1730). The resulting files can be committed to the repo so that you usually don't need NPM to work on `gleam` - unless you work on the documentation pages.

To build:

```
cd compiler-core/templates
npm install
npm run esbuild
git add dist/index.css dist/index.js
```

There's further potential for clean-up:
- We could move all of the docs-related JS into a subdirectory to make clear that it's separate from `prelude.js`
- We could run a formatter like `standard` on the JavaScript
- I think all of the code in `gleam.js` could be merged into `index.js` (or the other way around)

### CODE REVIEW

**Comment by aflatter** [comment]
@lpil Here we go 👍 Let me know what you think.

**Review by lpil — COMMENTED** [review]
Hello! Thanks for this!

Could you convert this to just having the files vendored in the repository, the same as we do for the existing assets? We don't want to depend on npm at all or have another build tool.

**Comment by aflatter** [comment]
> Hello! Thanks for this!
> 
> Could you convert this to just having the files vendored in the repository, the same as we do for the existing assets? We don't want to depend on npm at all or have another build tool.

Hmm, can you expand on your rationale here?

re `npm`: If we just put the minified versions of each library into the directory, it's hard to track the versions and update them as required.

re `esbuild`: Gives us a single `js`/`css` file to include and lets us work with `import` instead of the global scope - making things much easier to understand.

Though I can understand the urge to avoid any frontend-specific tooling, I think committing the resulting bundle to the repo strikes an okay balance: Usually you won't need to install/work with these things, but if you need to, it will make the work easy to understand.

**Comment by lpil** [comment]
It's not hard to keep track of versions, the version numbers commonly go both in the file name and the comment header of the file. It is simpler and easier to download a file than to install a package manager, a bundler, and run both.

Having 1 dependency in the global scope isn't difficult to understand, and continuing to use it that way means we don't need to rewrite any of the existing code.

We are not adding any new build tools to the Gleam compiler. We are actively working to remove other tools that are used in a fashion similar to how this PR works because the update workflow is confusing.

**Comment by lpil** [comment]
Closing this due to inactivity, please feel free to reopen!

**Pull request closed without merging**
