### PR TITLE
Add theme-color to documentation-layout

### PR DESCRIPTION
**Pull request by inoas**
See https://css-tricks.com/meta-theme-color-and-trickery/

### CODE REVIEW

**Comment by inoas** [comment]
Colours picked from current gleam `<header>`-element.

**Comment by inoas** [comment]
I think generally the spotlight/search icon could use some cta-ish-ness.

**Comment by inoas** [comment]
failing tests seem unrelated to me

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
