### PR TITLE
Fix a bug where a record constructor's argument would not have a doc string

### LINKED ISSUE #2631: Bug in how the doc site is generated
In this snippet of code
```gleam
pub type Wibble {
  Wobble(
    /// Documentation!!
    wabble: Int,
  )
}

pub fn main() {
  io.println("Hello from prova!")
}
```
The generated documentation looks like this. Notice how the doc comment `/// Documentation!` is also erroneously rendered as the main's documentation:
Screenshot 2024-03-02 alle 17 00 18

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This issue closes #2631

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
The documentation isn't shown at all now. Should we add it to the template?

**Comment by giacomocavalieri** [comment]
I think this is related to that issue I ran into with testing the generated docs I was talking to you the other day on discord. Locally it works fine but it doesn't end up in the test snapshots

**Comment by lpil** [comment]
Sorry, I've forgotten the detail in the rush of the release. What's the problem again?

**Comment by giacomocavalieri** [comment]
So when fixing when fixing [this issue](https://github.com/gleam-lang/gleam/issues/2617) I ran into some strange test behaviour I couldn't fix on my own.

To test that it works I've also updated the test function to include page docs, so far so good.
The problem is that when I run it the generated html has an empty [main element](https://github.com/gleam-lang/gleam/pull/2637/files#diff-affe2e9bf3502ba81b40568370d752e7a613f3599e35f96959b1d35c7ed5749cR226-R230)
I couldn't figure out why is that, what's even more strange is that I tried the fixed version of the compiler locally with make install and using that it works perfectly! My guess is that the test function is missing some important bit that the cli does but I couldn't figure out what.

My guess is that here there's a similar problem, things work perfectly if I install the patched version locally and run `gleam docs build` but somehow those pieces are missing from the test string that is getting snapped

**Comment by lpil** [comment]
Coolio. Is this something you're working on or should I take a look?

**Comment by giacomocavalieri** [comment]
It would be a great help if you could take a look at that 💖
Looking at the test code I couldn't figure it out on my own

**Comment by giacomocavalieri** [comment]
@lpil did you manage to have a look at this?

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
