### PR TITLE
Add warn if no fields are given in a record update

### PR DESCRIPTION
**Pull request by mrgleam**
The PR add the warning if no fields are given in a record update for issue #739

Screen Shot 2563-08-07 at 00 22 14

### CODE REVIEW

**Comment by mrgleam** [comment]
fot Test compiler / build_compiler_macos

Screen Shot 2563-08-07 at 09 23 22

What am I missing?

**Comment by QuinnWilton** [comment]
I don't see any reason this should be failing in CI. Have you tried repushing to trigger CI again and see whether the error goes away?

**Comment by mrgleam** [comment]
Try to trigger CI again.

**Comment by mrgleam** [comment]
I re-open PR for trigger CI again. but I got same error in build_compiler_macos.

**Comment by QuinnWilton** [comment]
@mrgleam I just noticed that the other open PR is failing for the same reason: https://github.com/gleam-lang/gleam/pull/743

**Comment by mrgleam** [comment]
Thank you @QuinnWilton

**Comment by mrgleam** [comment]
I'm guessing.
It because dependencies cache is incomplete.
Because commit number 4c0e24a.
CI for build on MacOS passed and i see, the dependencies cache not found.
Screen Shot 2563-08-09 at 10 53 43

**Comment by lpil** [comment]
Still failing. I'm going to merge anyway

**Pull request merged**
