### PR TITLE
Improve error message when accessing module aliases as names

### PR DESCRIPTION
**Pull request by sobolevn**
Please, suggest better wordings 🚀  

Closes https://github.com/gleam-lang/gleam/issues/3476

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Nice, thank you!

It is a name, so let's say that is being used as a value, and drop the bit about accessing the members for now.

Could you update the changelog too

**Comment by sobolevn** [comment]
Done!

**Review by lpil — APPROVED** [review]
Thank you!

**Comment by sobolevn** [comment]
Resolving conflicts :)

**Comment by sobolevn** [comment]
Oh no! Rebasing this properly, sorry :)
Not used to this workflow.

**Pull request merged**
