### PR TITLE
HighlightJS Gleam improvements

### PR DESCRIPTION
**Pull request by tynanbe**
Fix some bugs in the patterns. Improve pattern accuracy. Simplify.

Not extensively tested, but scanned over all of Gleam/Stdlib and didn't see any problems.

### CODE REVIEW

**Comment by lpil** [comment]
Thanks! This is a vendored copy of the upstream highlightjs-gleam library. The changes will need to be made to that project and then we can copy them over, rather than forking it here.

**Comment by tynanbe** [comment]
See: https://gitlab.com/greggreg/highlightjs-gleam/-/merge_requests/1

**Comment by lpil** [comment]
Fab! I'll merge this once it is in upstream.

**Comment by lpil** [comment]
Hmm no response from Greg, shall we merge this and worry about the library later? @tynanbe

**Comment by tynanbe** [comment]
I vote yes, @lpil. At some point it will need to move to the highlightjs repo proper anyway (https://github.com/highlightjs/highlight.js/tree/main/src/languages).

**Review by lpil — APPROVED** [review]
Fab, thank you!

**Pull request merged**
