### PR TITLE
Return more clear error when expecting functions

### LINKED ISSUE #510: Compiler errors not clear for type mismatches when expecting functions
Here is an example.

```rust
fn bar() -> Int {
    5
}

fn run(foo: fn() -> String) {
    foo()
}

fn demo() {
    run(bar)
}
```

Error message 

```
Expected type:

    String

Found type:

    Int
```

I would expect it to say Expected Type `fn () -> String` or have a message about expected return type.

### PR DESCRIPTION
**Pull request by gamebox**
Closes #510

### CODE REVIEW

**Comment by gamebox** [comment]
Example error, using above example(this is in the test)

```
error: Type mismatch

    ┌── :10:18 ───
    │
 10 │              run(bar)
    │                  ^^^
    │

Expected type:

    fn() -> String

Found type:

    fn() -> Int
```

**Comment by lpil** [comment]
Fantastic! Could we also have a test for when the arguments are different? For example `fn(Int) -> Int != fn(String) -> Int`

Thank you

**Comment by gamebox** [comment]
Example output for that case:

```
error: Type mismatch

    ┌── :10:18 ───
    │
 10 │              run(bar)
    │                  ^^^
    │

Expected type:

    fn(String) -> Int

Found type:

    fn(Int) -> Int
```

**Comment by gamebox** [comment]
Sure!

**Comment by lpil** [comment]
I've rebased these commits onto master, thank you!

**Pull request closed without merging**
