### PR TITLE
refactor: remove lazy_static in favor of OnceLock

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/gleam-lang/gleam/issues/2217

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Thank you!

**Comment by lpil** [comment]
Looks like there's some lint issues to fix!

**Comment by bartlomieju** [comment]
I ended up using `static`s and `OnceLock` instead of `const` and `OnceCell` to make clippy happy.

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
