### PR TITLE
Comment above case branch splits alternative clauses. #1990

### PR DESCRIPTION
**Pull request by Ashish020202**
closes   https://github.com/Ashish020202/gleam/pull/new/ashish/issue1190

commented case 
splited alternative clauses

### CODE REVIEW

**Comment by lpil** [comment]
Hey @Ashish020202 ! Thanks for the contribution. Did you forgot to push your changes perhaps? 😁

**Comment by Ashish020202** [comment]
Pls elaborate more about this issue I think I took some wrong assumption.

**Comment by Ashish020202** [comment]
case num {
  // 1 or 2
  1
  | 2 -> ...
}
I have to change in this format isn't it .
Or there is any other case .

**Comment by lpil** [comment]
The issue is that when a comment is added about an alternative pattern it now forces it to be wrapped onto multiple lines, this should not be the case.

The solution will be to use the `.group()` method on the printing document for the pattern (https://github.com/gleam-lang/gleam/issues/1990#issuecomment-1424704922)

**Pull request closed without merging**
