### PR TITLE
Add nix flake environment.

### PR DESCRIPTION
**Pull request by vic**
This branch adds a nix-flake for Gleam.

This will allow people using the [nix](https://nixos.org) package manager to build and run any commit of Gleam. Also allows contributors using nix to have a development environment with
all dependencies loaded and ready to `hack && cargo build`

See the guide on the Nix.md file.

### CODE REVIEW

**Comment by vic** [comment]
A few years ago I did an [asdf-plugin for gleam](https://github.com/asdf-community/asdf-gleam). In hopes it helped more people to get a running gleam fast and try it out. 

Since about a year I've been using nix for all my dependency needs instead of asdf. So here's my contribution again in hopes that more people can try gleam right away.

For example, my PR branch is runnable like this:

Screen Shot 2021-12-20 at 16 21 12

**Comment by vic** [comment]
Perhaps this could be the solution of #1277 for people using Nix.

**Comment by lpil** [comment]
While I think this is a great thing to have, I'm afraid I can't accept this as I'm not able to maintain it as I don't know enough about Nix. This will need to be maintained by somebody else in a different repo, as with the asdf plugin.

**Comment by vic** [comment]
I'll be moving this flake to a repo of mine.

Is it ok to mention how to use my external repo to get a gleam environment on this repo documentation? Maybe just a line or two so that people using nix can quickly get a full environment.

**Comment by lpil** [comment]
Yes I think that's a really good idea! Let's get it in there.

**Pull request closed without merging**
