### PR TITLE
Unlock unfresh deps

### PR DESCRIPTION
**Pull request by lpil**
Closes https://github.com/gleam-lang/gleam/issues/1356

### CODE REVIEW

**Comment by lpil** [comment]
@TanklesXL would you mind giving this a test before I merge? Seems to be working but it's fairly complex so would be good to get another pair of eyes.

**Comment by TanklesXL** [comment]
@lpil I'll give it a look tomorrow

**Comment by lpil** [comment]
Of course! No rush

**Comment by TanklesXL** [comment]
@lpil I pulled this branch but am still able to replicate issue #1356 on my end, changing line `gleam_erlang = "~> 0.4"` to `gleam_erlang = "~> 0.3"` and rerunning `gleam deps download` still results in having `gleam_erlang  v0.4.0` downloaded, it is also listed in `gleam deps list`

**Comment by lpil** [comment]
That'll be because ~> 0.3 permits 0.4.0, you'll need to specify ~> 0.3.0 to disallow 0.4.0

**Comment by TanklesXL** [comment]
Oh I'm dumb 😂

**Comment by lpil** [comment]
Not dumb at all! It's not obvious what these operators mean 

Here: https://hexdocs.pm/elixir/Version.html#module-requirements

I'm going to write up some docs for Gleam users too

**Comment by TanklesXL** [comment]
@lpil it looks like it works sometimes, given these dependencies
```
[dependencies]
gleam_stdlib = "~> 0.18"
gleam_otp = "~> 0.3"
gleam_erlang = "~> 0.4.0"
snag = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 0.4"
``` 
when i switch `gleeunit` to `~> 0.3.0` it successfully downgrades it, but when i try the same thing with `gleam_erlang` and put it to `~> 0.3.0` it doesn't result in any change and the manifest still specifies `gleam_erlang version 0.4.0`

**Comment by lpil** [comment]
Well spotted, thank you

**Comment by lpil** [comment]
I've done some investigation and I think the work in this PR is correct, but there's an issue with the version resolver. I'm gunna merge this and make an issue

**Comment by TanklesXL** [comment]
Awesome! Glad I could help 😃

**Comment by lpil** [comment]
Thank you <3

**Pull request merged**
