### PR TITLE
fixed semicolon in readme

### PR DESCRIPTION
**Pull request by dym-sh**
9BB3E6B0-50B5-4480-A96A-E326F63E7275

ಠ_ಠ

### CODE REVIEW

**Comment by lpil** [comment]
Looks like this broke the fake syntax highlighting. Doh :( 

I'll put it back until we have #477

**Comment by dym-sh** [comment]
but it works for mdBook: https://github.com/gleam-lang/website/blob/master/src/README.md

so the problem is in Linguist's rust parser?

**Comment by lpil** [comment]
That's right, GitHub doesn't yet support Gleam

**Comment by dym-sh** [comment]
i mean the rust parsing/highlighting stops once it encounters "semicolon expected"
but the mdBook in docs also has `rust` for the same code and highlights entire block regardless

**Comment by lpil** [comment]
Yes, that's right. I'm not sure why they do that

**Pull request merged**
