### PR TITLE
Extract into variable code action

### LINKED ISSUE #3934: Extract variable code action
An action that extracts a highlighted value and replaces it with a variable
```gleam
pub fn main() {
  list.map([1, 2, 3], run)
  #        ^^^^^^^^^
}
```

```gleam
pub fn main() {
  let value = [1, 2, 3]
  list.map(value, run)
}
```

### PR DESCRIPTION
**Pull request by giacomocavalieri**
This PR closes #3934

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
Beautiful! Wanna update the changelog? 💜

**Comment by giacomocavalieri** [comment]
Oops totally forgot about it, thank you!

**Review by lpil — COMMENTED** [review]
Could you rebase please? The other changelog changes have cause conflicts

**Comment by giacomocavalieri** [comment]
Done! Sorry for the inconvenience

**Review by lpil — APPROVED** [review]
Thank you!!

**Pull request merged**
